### ISSUE TITLE
Upgrade sourcegraph

### ISSUE THREAD

**Issue by jvperrin** [ocf/sourcegraph#3]
The version we're on now (3.0.1, from Feb 2019) is pretty old compared to the most recent stable one (3.16.0 as of May 2020). They are monthly releases though and apparently no manual migrations steps should be needed between these minor version numbers, although I've found config file changes are definitely needed and that downgrading again is not necessarily a smooth process...

I did try upgrading previously, but hit some problems, the key of which was that anonymous access was removed in newer versions and is something we rely on currently. Since all our code is open source, there's not really any need for a login. Maybe we could use the version of sourcegraph that they host for github and open source repos, but having our own has been kinda nice to not need to filter by repo or anything.

**Comment by nikhiljha** [comment]
It would be nice if it didn't have to be behind auth but I don't think that's a *dealbreaker*.
